-- Generated from Pokemon Yellow Legacy v1.0.10 source.
-- Rates are fallbacks only; installation preserves a live edition's rate.
return {
  CERULEAN_CAVE_1F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 64, species = "RHYDON" },
        { level = 63, species = "GOLEM" },
        { level = 62, species = "ELECTRODE" },
        { level = 61, species = "LICKITUNG" },
        { level = 65, species = "CHANSEY" },
        { level = 60, species = "DITTO" },
        { level = 64, species = "VILEPLUME" },
        { level = 63, species = "VICTREEBEL" },
        { level = 64, species = "RAICHU" },
        { level = 65, species = "RAICHU" },
      },
    },
  },
  CERULEAN_CAVE_2F = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 64, species = "GOLEM" },
        { level = 63, species = "SANDSLASH" },
        { level = 62, species = "WIGGLYTUFF" },
        { level = 61, species = "MAROWAK" },
        { level = 65, species = "DODRIO" },
        { level = 60, species = "DITTO" },
        { level = 64, species = "MAGNETON" },
        { level = 63, species = "CHANSEY" },
        { level = 64, species = "RAICHU" },
        { level = 65, species = "RAICHU" },
      },
    },
  },
  CERULEAN_CAVE_B1F = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 64, species = "HYPNO" },
        { level = 63, species = "GOLDUCK" },
        { level = 62, species = "GOLBAT" },
        { level = 61, species = "SANDSLASH" },
        { level = 65, species = "PARASECT" },
        { level = 60, species = "SLOWBRO" },
        { level = 64, species = "KADABRA" },
        { level = 63, species = "DITTO" },
        { level = 64, species = "DITTO" },
        { level = 65, species = "ALAKAZAM" },
      },
    },
  },
  DIGLETTS_CAVE = {
    grass = {
      fallbackRate = 20,
      slots = {
        { level = 18, species = "DIGLETT" },
        { level = 19, species = "DIGLETT" },
        { level = 17, species = "DIGLETT" },
        { level = 20, species = "DIGLETT" },
        { level = 16, species = "DIGLETT" },
        { level = 15, species = "DIGLETT" },
        { level = 21, species = "DIGLETT" },
        { level = 22, species = "DIGLETT" },
        { level = 24, species = "DUGTRIO" },
        { level = 24, species = "DUGTRIO" },
      },
    },
  },
  MT_MOON_1F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 8, species = "ZUBAT" },
        { level = 9, species = "ZUBAT" },
        { level = 10, species = "GEODUDE" },
        { level = 6, species = "ZUBAT" },
        { level = 7, species = "ZUBAT" },
        { level = 10, species = "SANDSHREW" },
        { level = 10, species = "GEODUDE" },
        { level = 11, species = "SANDSHREW" },
        { level = 12, species = "SANDSHREW" },
        { level = 12, species = "CLEFAIRY" },
      },
    },
  },
  MT_MOON_B1F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 8, species = "ZUBAT" },
        { level = 9, species = "ZUBAT" },
        { level = 10, species = "ZUBAT" },
        { level = 10, species = "GEODUDE" },
        { level = 11, species = "GEODUDE" },
        { level = 11, species = "ZUBAT" },
        { level = 9, species = "PARAS" },
        { level = 11, species = "PARAS" },
        { level = 10, species = "CLEFAIRY" },
        { level = 12, species = "CLEFAIRY" },
      },
    },
  },
  MT_MOON_B2F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 10, species = "ZUBAT" },
        { level = 11, species = "GEODUDE" },
        { level = 13, species = "PARAS" },
        { level = 11, species = "ZUBAT" },
        { level = 11, species = "ZUBAT" },
        { level = 12, species = "ZUBAT" },
        { level = 13, species = "ZUBAT" },
        { level = 9, species = "CLEFAIRY" },
        { level = 12, species = "CLEFAIRY" },
        { level = 15, species = "CLEFAIRY" },
      },
    },
  },
  POKEMON_MANSION_1F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 34, species = "RATTATA" },
        { level = 34, species = "RATICATE" },
        { level = 33, species = "GRIMER" },
        { level = 36, species = "GROWLITHE" },
        { level = 37, species = "RATTATA" },
        { level = 37, species = "RATICATE" },
        { level = 32, species = "GROWLITHE" },
        { level = 36, species = "GRIMER" },
        { level = 40, species = "MAGMAR" },
        { level = 45, species = "MAGMAR" },
      },
    },
  },
  POKEMON_MANSION_2F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 37, species = "RATTATA" },
        { level = 37, species = "RATICATE" },
        { level = 36, species = "GRIMER" },
        { level = 39, species = "GRIMER" },
        { level = 40, species = "MUK" },
        { level = 40, species = "RATICATE" },
        { level = 42, species = "MUK" },
        { level = 40, species = "MAGMAR" },
        { level = 42, species = "MAGMAR" },
        { level = 45, species = "MAGMAR" },
      },
    },
  },
  POKEMON_MANSION_3F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 37, species = "RATTATA" },
        { level = 37, species = "RATICATE" },
        { level = 36, species = "GRIMER" },
        { level = 39, species = "GRIMER" },
        { level = 40, species = "MUK" },
        { level = 40, species = "RATICATE" },
        { level = 42, species = "MUK" },
        { level = 40, species = "MAGMAR" },
        { level = 42, species = "MAGMAR" },
        { level = 45, species = "MAGMAR" },
      },
    },
  },
  POKEMON_MANSION_B1F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 37, species = "RATICATE" },
        { level = 37, species = "MAGMAR" },
        { level = 36, species = "GRIMER" },
        { level = 39, species = "GRIMER" },
        { level = 40, species = "MUK" },
        { level = 40, species = "RATICATE" },
        { level = 7, species = "DITTO" },
        { level = 40, species = "MAGMAR" },
        { level = 25, species = "DITTO" },
        { level = 30, species = "DITTO" },
      },
    },
  },
  POKEMON_TOWER_3F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 20, species = "GASTLY" },
        { level = 21, species = "GASTLY" },
        { level = 22, species = "GASTLY" },
        { level = 23, species = "GASTLY" },
        { level = 24, species = "GASTLY" },
        { level = 19, species = "GASTLY" },
        { level = 18, species = "GASTLY" },
        { level = 25, species = "GASTLY" },
        { level = 25, species = "HAUNTER" },
        { level = 25, species = "HAUNTER" },
      },
    },
  },
  POKEMON_TOWER_4F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 20, species = "GASTLY" },
        { level = 21, species = "GASTLY" },
        { level = 22, species = "GASTLY" },
        { level = 23, species = "GASTLY" },
        { level = 24, species = "GASTLY" },
        { level = 19, species = "GASTLY" },
        { level = 19, species = "GASTLY" },
        { level = 25, species = "GASTLY" },
        { level = 24, species = "HAUNTER" },
        { level = 25, species = "HAUNTER" },
      },
    },
  },
  POKEMON_TOWER_5F = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 22, species = "GASTLY" },
        { level = 23, species = "GASTLY" },
        { level = 24, species = "GASTLY" },
        { level = 25, species = "GASTLY" },
        { level = 26, species = "GASTLY" },
        { level = 21, species = "GASTLY" },
        { level = 24, species = "CUBONE" },
        { level = 27, species = "GASTLY" },
        { level = 27, species = "HAUNTER" },
        { level = 27, species = "HAUNTER" },
      },
    },
  },
  POKEMON_TOWER_6F = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 23, species = "GASTLY" },
        { level = 24, species = "GASTLY" },
        { level = 25, species = "GASTLY" },
        { level = 26, species = "GASTLY" },
        { level = 27, species = "GASTLY" },
        { level = 23, species = "GASTLY" },
        { level = 24, species = "CUBONE" },
        { level = 28, species = "HAUNTER" },
        { level = 29, species = "HAUNTER" },
        { level = 30, species = "GENGAR" },
      },
    },
  },
  POKEMON_TOWER_7F = {
    grass = {
      fallbackRate = 20,
      slots = {
        { level = 24, species = "GASTLY" },
        { level = 25, species = "GASTLY" },
        { level = 26, species = "GASTLY" },
        { level = 27, species = "GASTLY" },
        { level = 28, species = "GASTLY" },
        { level = 23, species = "GASTLY" },
        { level = 24, species = "CUBONE" },
        { level = 28, species = "HAUNTER" },
        { level = 29, species = "HAUNTER" },
        { level = 32, species = "GENGAR" },
      },
    },
  },
  POWER_PLANT = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 30, species = "MAGNEMITE" },
        { level = 33, species = "MAGNETON" },
        { level = 35, species = "MAGNETON" },
        { level = 33, species = "VOLTORB" },
        { level = 37, species = "ELECTRODE" },
        { level = 33, species = "GRIMER" },
        { level = 37, species = "MUK" },
        { level = 38, species = "ELECTABUZZ" },
        { level = 39, species = "ELECTABUZZ" },
        { level = 33, species = "RAICHU" },
      },
    },
  },
  ROCK_TUNNEL_1F = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 15, species = "ZUBAT" },
        { level = 16, species = "GEODUDE" },
        { level = 17, species = "MACHOP" },
        { level = 19, species = "ZUBAT" },
        { level = 18, species = "GEODUDE" },
        { level = 20, species = "GEODUDE" },
        { level = 21, species = "ZUBAT" },
        { level = 17, species = "CUBONE" },
        { level = 19, species = "CUBONE" },
        { level = 21, species = "CUBONE" },
      },
    },
  },
  ROCK_TUNNEL_B1F = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 20, species = "ZUBAT" },
        { level = 17, species = "GEODUDE" },
        { level = 18, species = "MACHOP" },
        { level = 21, species = "ZUBAT" },
        { level = 22, species = "ZUBAT" },
        { level = 21, species = "GEODUDE" },
        { level = 20, species = "MACHOP" },
        { level = 17, species = "ONIX" },
        { level = 18, species = "ONIX" },
        { level = 22, species = "ONIX" },
      },
    },
  },
  ROUTE_1 = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 3, species = "PIDGEY" },
        { level = 4, species = "PIDGEY" },
        { level = 2, species = "RATTATA" },
        { level = 3, species = "RATTATA" },
        { level = 2, species = "PIDGEY" },
        { level = 3, species = "PIDGEY" },
        { level = 5, species = "PIDGEY" },
        { level = 4, species = "RATTATA" },
        { level = 5, species = "SPEAROW" },
        { level = 6, species = "SPEAROW" },
      },
    },
  },
  ROUTE_10 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 16, species = "MAGNEMITE" },
        { level = 20, species = "RATICATE" },
        { level = 18, species = "MAGNEMITE" },
        { level = 20, species = "MAGNEMITE" },
        { level = 17, species = "NIDORAN_M" },
        { level = 17, species = "NIDORAN_F" },
        { level = 22, species = "MAGNEMITE" },
        { level = 18, species = "MACHOP" },
        { level = 19, species = "MACHOP" },
        { level = 20, species = "MACHOP" },
      },
    },
  },
  ROUTE_11 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 16, species = "PIDGEY" },
        { level = 15, species = "RATTATA" },
        { level = 18, species = "SANDSHREW" },
        { level = 17, species = "DROWZEE" },
        { level = 17, species = "EKANS" },
        { level = 18, species = "DROWZEE" },
        { level = 20, species = "PIDGEOTTO" },
        { level = 19, species = "MAGNEMITE" },
        { level = 19, species = "DROWZEE" },
        { level = 20, species = "DROWZEE" },
      },
    },
  },
  ROUTE_12 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 25, species = "ODDISH" },
        { level = 25, species = "BELLSPROUT" },
        { level = 28, species = "PIDGEY" },
        { level = 28, species = "PIDGEOTTO" },
        { level = 28, species = "ODDISH" },
        { level = 29, species = "TANGELA" },
        { level = 29, species = "GLOOM" },
        { level = 29, species = "WEEPINBELL" },
        { level = 26, species = "FARFETCHD" },
        { level = 31, species = "FARFETCHD" },
      },
    },
    water = {
      fallbackRate = 3,
      slots = {
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWBRO" },
        { level = 20, species = "SLOWBRO" },
      },
    },
  },
  ROUTE_13 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 25, species = "ODDISH" },
        { level = 25, species = "BELLSPROUT" },
        { level = 28, species = "PIDGEOTTO" },
        { level = 28, species = "PIDGEY" },
        { level = 27, species = "GLOOM" },
        { level = 27, species = "SCYTHER" },
        { level = 29, species = "WEEPINBELL" },
        { level = 29, species = "WEEPINBELL" },
        { level = 26, species = "FARFETCHD" },
        { level = 33, species = "FARFETCHD" },
      },
    },
    water = {
      fallbackRate = 3,
      slots = {
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWPOKE" },
        { level = 15, species = "SLOWBRO" },
        { level = 20, species = "SLOWBRO" },
      },
    },
  },
  ROUTE_14 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 26, species = "ODDISH" },
        { level = 26, species = "BELLSPROUT" },
        { level = 24, species = "WEEPINBELL" },
        { level = 30, species = "PIDGEOTTO" },
        { level = 28, species = "GLOOM" },
        { level = 28, species = "SCYTHER" },
        { level = 30, species = "GLOOM" },
        { level = 28, species = "VENONAT" },
        { level = 27, species = "VENONAT" },
        { level = 33, species = "VENOMOTH" },
      },
    },
  },
  ROUTE_15 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 26, species = "ODDISH" },
        { level = 26, species = "BELLSPROUT" },
        { level = 24, species = "VENONAT" },
        { level = 32, species = "PIDGEOTTO" },
        { level = 28, species = "ODDISH" },
        { level = 28, species = "BELLSPROUT" },
        { level = 30, species = "GLOOM" },
        { level = 30, species = "WEEPINBELL" },
        { level = 30, species = "VENOMOTH" },
        { level = 34, species = "VENOMOTH" },
      },
    },
  },
  ROUTE_16 = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 22, species = "SPEAROW" },
        { level = 22, species = "DODUO" },
        { level = 23, species = "RATTATA" },
        { level = 24, species = "DODUO" },
        { level = 24, species = "GRIMER" },
        { level = 26, species = "DODUO" },
        { level = 23, species = "SPEAROW" },
        { level = 24, species = "FEAROW" },
        { level = 25, species = "RATICATE" },
        { level = 26, species = "RATICATE" },
      },
    },
  },
  ROUTE_17 = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 26, species = "DODUO" },
        { level = 27, species = "FEAROW" },
        { level = 27, species = "DODUO" },
        { level = 28, species = "GRIMER" },
        { level = 28, species = "PONYTA" },
        { level = 29, species = "GRIMER" },
        { level = 29, species = "FEAROW" },
        { level = 28, species = "DODUO" },
        { level = 32, species = "PONYTA" },
        { level = 31, species = "DODRIO" },
      },
    },
  },
  ROUTE_18 = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 25, species = "SPEAROW" },
        { level = 27, species = "DODUO" },
        { level = 23, species = "RATTATA" },
        { level = 28, species = "DODUO" },
        { level = 28, species = "RATICATE" },
        { level = 29, species = "DODUO" },
        { level = 28, species = "FEAROW" },
        { level = 29, species = "FEAROW" },
        { level = 31, species = "RATICATE" },
        { level = 32, species = "RATICATE" },
      },
    },
  },
  ROUTE_19 = {
    water = {
      fallbackRate = 5,
      slots = {
        { level = 20, species = "TENTACOOL" },
        { level = 10, species = "TENTACOOL" },
        { level = 15, species = "TENTACOOL" },
        { level = 5, species = "TENTACOOL" },
        { level = 15, species = "TENTACOOL" },
        { level = 20, species = "TENTACOOL" },
        { level = 25, species = "TENTACOOL" },
        { level = 30, species = "TENTACRUEL" },
        { level = 35, species = "TENTACRUEL" },
        { level = 40, species = "TENTACRUEL" },
      },
    },
  },
  ROUTE_2 = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 5, species = "RATTATA" },
        { level = 5, species = "PIDGEY" },
        { level = 6, species = "NIDORAN_F" },
        { level = 6, species = "NIDORAN_M" },
        { level = 5, species = "VULPIX" },
        { level = 6, species = "PIDGEY" },
        { level = 7, species = "VULPIX" },
        { level = 8, species = "RATTATA" },
        { level = 8, species = "PIDGEY" },
        { level = 8, species = "PIDGEY" },
      },
    },
  },
  ROUTE_20 = {
    water = {
      fallbackRate = 5,
      slots = {
        { level = 20, species = "TENTACOOL" },
        { level = 10, species = "TENTACOOL" },
        { level = 15, species = "TENTACOOL" },
        { level = 5, species = "TENTACOOL" },
        { level = 15, species = "TENTACOOL" },
        { level = 20, species = "TENTACOOL" },
        { level = 25, species = "TENTACOOL" },
        { level = 30, species = "TENTACRUEL" },
        { level = 35, species = "TENTACRUEL" },
        { level = 40, species = "TENTACRUEL" },
      },
    },
  },
  ROUTE_21 = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 25, species = "PIDGEY" },
        { level = 23, species = "RATTATA" },
        { level = 23, species = "PIDGEY" },
        { level = 21, species = "PIDGEY" },
        { level = 27, species = "MR_MIME" },
        { level = 25, species = "RATTATA" },
        { level = 25, species = "RATICATE" },
        { level = 27, species = "PIDGEOTTO" },
        { level = 29, species = "PIDGEOTTO" },
        { level = 30, species = "PIDGEOT" },
      },
    },
    water = {
      fallbackRate = 5,
      slots = {
        { level = 20, species = "TENTACOOL" },
        { level = 10, species = "TENTACOOL" },
        { level = 15, species = "TENTACOOL" },
        { level = 5, species = "TENTACOOL" },
        { level = 15, species = "TENTACOOL" },
        { level = 20, species = "TENTACOOL" },
        { level = 25, species = "TENTACOOL" },
        { level = 30, species = "TENTACRUEL" },
        { level = 35, species = "TENTACRUEL" },
        { level = 40, species = "TENTACRUEL" },
      },
    },
  },
  ROUTE_22 = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 3, species = "NIDORAN_M" },
        { level = 4, species = "MANKEY" },
        { level = 3, species = "NIDORAN_F" },
        { level = 4, species = "NIDORAN_M" },
        { level = 5, species = "SPEAROW" },
        { level = 4, species = "NIDORAN_F" },
        { level = 5, species = "MANKEY" },
        { level = 6, species = "SPEAROW" },
        { level = 5, species = "RATTATA" },
        { level = 5, species = "RATTATA" },
      },
    },
  },
  ROUTE_23 = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 44, species = "NIDORINO" },
        { level = 44, species = "NIDORINA" },
        { level = 51, species = "PRIMEAPE" },
        { level = 49, species = "NIDOKING" },
        { level = 49, species = "NIDOQUEEN" },
        { level = 50, species = "FEAROW" },
        { level = 5, species = "SQUIRTLE" },
        { level = 5, species = "BULBASAUR" },
        { level = 5, species = "CHARMANDER" },
        { level = 5, species = "EEVEE" },
      },
    },
  },
  ROUTE_24 = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 12, species = "PIDGEY" },
        { level = 12, species = "BELLSPROUT" },
        { level = 13, species = "ABRA" },
        { level = 14, species = "ODDISH" },
        { level = 14, species = "BELLSPROUT" },
        { level = 15, species = "PIDGEY" },
        { level = 13, species = "VENONAT" },
        { level = 16, species = "VENONAT" },
        { level = 17, species = "PIDGEY" },
        { level = 17, species = "PIDGEOTTO" },
      },
    },
  },
  ROUTE_25 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 12, species = "PIDGEY" },
        { level = 12, species = "BELLSPROUT" },
        { level = 13, species = "ABRA" },
        { level = 14, species = "ODDISH" },
        { level = 14, species = "BELLSPROUT" },
        { level = 15, species = "PIDGEY" },
        { level = 13, species = "VENONAT" },
        { level = 16, species = "VENONAT" },
        { level = 17, species = "PIDGEY" },
        { level = 17, species = "PIDGEOTTO" },
      },
    },
  },
  ROUTE_3 = {
    grass = {
      fallbackRate = 20,
      slots = {
        { level = 8, species = "SPEAROW" },
        { level = 9, species = "MANKEY" },
        { level = 10, species = "ODDISH" },
        { level = 9, species = "JIGGLYPUFF" },
        { level = 10, species = "RATTATA" },
        { level = 10, species = "RATTATA" },
        { level = 11, species = "ODDISH" },
        { level = 12, species = "RATTATA" },
        { level = 13, species = "SPEAROW" },
        { level = 14, species = "SPEAROW" },
      },
    },
  },
  ROUTE_4 = {
    grass = {
      fallbackRate = 20,
      slots = {
        { level = 11, species = "SPEAROW" },
        { level = 11, species = "EKANS" },
        { level = 12, species = "MANKEY" },
        { level = 13, species = "FARFETCHD" },
        { level = 13, species = "SANDSHREW" },
        { level = 13, species = "RATTATA" },
        { level = 14, species = "SANDSHREW" },
        { level = 12, species = "PSYDUCK" },
        { level = 13, species = "PSYDUCK" },
        { level = 15, species = "PSYDUCK" },
      },
    },
  },
  ROUTE_5 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 15, species = "MEOWTH" },
        { level = 14, species = "RATTATA" },
        { level = 13, species = "ABRA" },
        { level = 16, species = "FARFETCHD" },
        { level = 16, species = "RATTATA" },
        { level = 17, species = "PIDGEY" },
        { level = 17, species = "PIDGEOTTO" },
        { level = 13, species = "JIGGLYPUFF" },
        { level = 15, species = "JIGGLYPUFF" },
        { level = 17, species = "JIGGLYPUFF" },
      },
    },
  },
  ROUTE_6 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 15, species = "PIDGEY" },
        { level = 14, species = "RATTATA" },
        { level = 14, species = "ABRA" },
        { level = 16, species = "PIDGEY" },
        { level = 16, species = "LICKITUNG" },
        { level = 15, species = "PSYDUCK" },
        { level = 17, species = "PIDGEOTTO" },
        { level = 16, species = "MAGNEMITE" },
        { level = 17, species = "MAGNEMITE" },
        { level = 19, species = "MAGNEMITE" },
      },
    },
    water = {
      fallbackRate = 3,
      slots = {
        { level = 10, species = "PSYDUCK" },
        { level = 15, species = "PSYDUCK" },
        { level = 15, species = "PSYDUCK" },
        { level = 15, species = "PSYDUCK" },
        { level = 15, species = "PSYDUCK" },
        { level = 20, species = "PSYDUCK" },
        { level = 25, species = "GOLDUCK" },
        { level = 30, species = "GOLDUCK" },
        { level = 30, species = "GOLDUCK" },
        { level = 35, species = "GOLDUCK" },
      },
    },
  },
  ROUTE_7 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 20, species = "VULPIX" },
        { level = 22, species = "PIDGEY" },
        { level = 20, species = "RATTATA" },
        { level = 22, species = "KOFFING" },
        { level = 23, species = "KOFFING" },
        { level = 24, species = "PIDGEOTTO" },
        { level = 26, species = "ABRA" },
        { level = 19, species = "JIGGLYPUFF" },
        { level = 24, species = "JIGGLYPUFF" },
        { level = 30, species = "JIGGLYPUFF" },
      },
    },
  },
  ROUTE_8 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 20, species = "GROWLITHE" },
        { level = 22, species = "PIDGEY" },
        { level = 20, species = "RATTATA" },
        { level = 17, species = "ABRA" },
        { level = 18, species = "ABRA" },
        { level = 24, species = "PIDGEOTTO" },
        { level = 19, species = "ABRA" },
        { level = 24, species = "JIGGLYPUFF" },
        { level = 24, species = "KADABRA" },
        { level = 28, species = "KADABRA" },
      },
    },
  },
  ROUTE_9 = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 16, species = "NIDORAN_M" },
        { level = 16, species = "NIDORAN_F" },
        { level = 18, species = "RATTATA" },
        { level = 18, species = "LICKITUNG" },
        { level = 18, species = "NIDORINA" },
        { level = 18, species = "NIDORINO" },
        { level = 18, species = "SPEAROW" },
        { level = 20, species = "FEAROW" },
        { level = 21, species = "PINSIR" },
        { level = 23, species = "PINSIR" },
      },
    },
  },
  SAFARI_ZONE_CENTER = {
    grass = {
      fallbackRate = 30,
      slots = {
        { level = 32, species = "NIDORINO" },
        { level = 32, species = "NIDORINA" },
        { level = 35, species = "EXEGGCUTE" },
        { level = 34, species = "RHYHORN" },
        { level = 36, species = "NIDOKING" },
        { level = 36, species = "NIDOQUEEN" },
        { level = 36, species = "WEEPINBELL" },
        { level = 37, species = "WEEPINBELL" },
        { level = 35, species = "TANGELA" },
        { level = 32, species = "CHANSEY" },
      },
    },
  },
  SAFARI_ZONE_EAST = {
    grass = {
      fallbackRate = 30,
      slots = {
        { level = 32, species = "TAUROS" },
        { level = 33, species = "RHYHORN" },
        { level = 35, species = "EXEGGCUTE" },
        { level = 34, species = "TAUROS" },
        { level = 36, species = "CUBONE" },
        { level = 36, species = "MAROWAK" },
        { level = 36, species = "SCYTHER" },
        { level = 37, species = "PINSIR" },
        { level = 35, species = "CHANSEY" },
        { level = 40, species = "SCYTHER" },
      },
    },
  },
  SAFARI_ZONE_NORTH = {
    grass = {
      fallbackRate = 30,
      slots = {
        { level = 32, species = "NIDOQUEEN" },
        { level = 33, species = "NIDOKING" },
        { level = 35, species = "CUBONE" },
        { level = 34, species = "KANGASKHAN" },
        { level = 34, species = "RHYHORN" },
        { level = 36, species = "MAROWAK" },
        { level = 35, species = "KANGASKHAN" },
        { level = 35, species = "RHYHORN" },
        { level = 36, species = "RHYHORN" },
        { level = 40, species = "CHANSEY" },
      },
    },
  },
  SAFARI_ZONE_WEST = {
    grass = {
      fallbackRate = 30,
      slots = {
        { level = 35, species = "PARASECT" },
        { level = 33, species = "VENOMOTH" },
        { level = 35, species = "PINSIR" },
        { level = 34, species = "SCYTHER" },
        { level = 36, species = "BUTTERFREE" },
        { level = 36, species = "BEEDRILL" },
        { level = 36, species = "DODRIO" },
        { level = 36, species = "FEAROW" },
        { level = 36, species = "PIDGEOT" },
        { level = 40, species = "PIDGEOT" },
      },
    },
  },
  SEAFOAM_ISLANDS_1F = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 25, species = "ZUBAT" },
        { level = 30, species = "KRABBY" },
        { level = 32, species = "KRABBY" },
        { level = 33, species = "GOLBAT" },
        { level = 35, species = "GOLBAT" },
        { level = 32, species = "SLOWPOKE" },
        { level = 35, species = "SLOWPOKE" },
        { level = 32, species = "GOLBAT" },
        { level = 35, species = "JYNX" },
        { level = 36, species = "JYNX" },
      },
    },
  },
  SEAFOAM_ISLANDS_B1F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 27, species = "ZUBAT" },
        { level = 26, species = "KRABBY" },
        { level = 36, species = "GOLBAT" },
        { level = 38, species = "KINGLER" },
        { level = 37, species = "GOLBAT" },
        { level = 33, species = "SLOWPOKE" },
        { level = 38, species = "JYNX" },
        { level = 28, species = "KINGLER" },
        { level = 35, species = "SLOWPOKE" },
        { level = 38, species = "SLOWBRO" },
      },
    },
  },
  SEAFOAM_ISLANDS_B2F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 27, species = "ZUBAT" },
        { level = 26, species = "KRABBY" },
        { level = 36, species = "GOLBAT" },
        { level = 38, species = "KINGLER" },
        { level = 37, species = "GOLBAT" },
        { level = 33, species = "SLOWPOKE" },
        { level = 38, species = "JYNX" },
        { level = 28, species = "KINGLER" },
        { level = 35, species = "SLOWPOKE" },
        { level = 38, species = "SLOWBRO" },
      },
    },
  },
  SEAFOAM_ISLANDS_B3F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 36, species = "GOLBAT" },
        { level = 36, species = "ZUBAT" },
        { level = 38, species = "JYNX" },
        { level = 39, species = "KINGLER" },
        { level = 34, species = "SEEL" },
        { level = 35, species = "SEEL" },
        { level = 40, species = "JYNX" },
        { level = 45, species = "GOLBAT" },
        { level = 39, species = "DEWGONG" },
        { level = 40, species = "DEWGONG" },
      },
    },
    water = {
      fallbackRate = 5,
      slots = {
        { level = 25, species = "TENTACOOL" },
        { level = 30, species = "TENTACOOL" },
        { level = 20, species = "TENTACOOL" },
        { level = 30, species = "STARYU" },
        { level = 35, species = "TENTACOOL" },
        { level = 30, species = "STARYU" },
        { level = 40, species = "TENTACRUEL" },
        { level = 30, species = "STARYU" },
        { level = 30, species = "STARYU" },
        { level = 30, species = "STARYU" },
      },
    },
  },
  SEAFOAM_ISLANDS_B4F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 36, species = "GOLBAT" },
        { level = 36, species = "ZUBAT" },
        { level = 38, species = "JYNX" },
        { level = 39, species = "KINGLER" },
        { level = 34, species = "SEEL" },
        { level = 35, species = "SEEL" },
        { level = 40, species = "JYNX" },
        { level = 45, species = "GOLBAT" },
        { level = 39, species = "DEWGONG" },
        { level = 40, species = "DEWGONG" },
      },
    },
    water = {
      fallbackRate = 5,
      slots = {
        { level = 25, species = "TENTACOOL" },
        { level = 30, species = "TENTACOOL" },
        { level = 20, species = "TENTACOOL" },
        { level = 30, species = "STARYU" },
        { level = 35, species = "TENTACOOL" },
        { level = 30, species = "STARYU" },
        { level = 40, species = "TENTACRUEL" },
        { level = 30, species = "STARYU" },
        { level = 30, species = "STARYU" },
        { level = 30, species = "STARYU" },
      },
    },
  },
  VICTORY_ROAD_1F = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 46, species = "GRAVELER" },
        { level = 42, species = "RHYHORN" },
        { level = 45, species = "GRAVELER" },
        { level = 46, species = "MACHAMP" },
        { level = 44, species = "GOLBAT" },
        { level = 46, species = "GOLEM" },
        { level = 43, species = "ONIX" },
        { level = 45, species = "ONIX" },
        { level = 48, species = "HITMONCHAN" },
        { level = 48, species = "HITMONCHAN" },
      },
    },
  },
  VICTORY_ROAD_2F = {
    grass = {
      fallbackRate = 10,
      slots = {
        { level = 46, species = "GRAVELER" },
        { level = 42, species = "RHYHORN" },
        { level = 45, species = "GRAVELER" },
        { level = 46, species = "MACHAMP" },
        { level = 44, species = "GOLBAT" },
        { level = 45, species = "GOLEM" },
        { level = 45, species = "ONIX" },
        { level = 47, species = "RHYDON" },
        { level = 48, species = "HITMONLEE" },
        { level = 48, species = "HITMONLEE" },
      },
    },
  },
  VICTORY_ROAD_3F = {
    grass = {
      fallbackRate = 15,
      slots = {
        { level = 47, species = "GRAVELER" },
        { level = 43, species = "GEODUDE" },
        { level = 46, species = "MACHAMP" },
        { level = 47, species = "GOLBAT" },
        { level = 45, species = "GOLEM" },
        { level = 46, species = "ONIX" },
        { level = 46, species = "RHYDON" },
        { level = 48, species = "HITMONCHAN" },
        { level = 48, species = "HITMONLEE" },
        { level = 48, species = "HITMONLEE" },
      },
    },
  },
  VIRIDIAN_FOREST = {
    grass = {
      fallbackRate = 25,
      slots = {
        { level = 4, species = "CATERPIE" },
        { level = 4, species = "WEEDLE" },
        { level = 7, species = "PIDGEY" },
        { level = 7, species = "KAKUNA" },
        { level = 5, species = "ODDISH" },
        { level = 6, species = "METAPOD" },
        { level = 6, species = "ODDISH" },
        { level = 7, species = "KAKUNA" },
        { level = 8, species = "PIDGEY" },
        { level = 9, species = "PIDGEOTTO" },
      },
    },
  },
}
