-- Generated from Pokemon Yellow Legacy v1.0.10 source.
-- Old/Good Rod pools are global; Super Rod pools are map-specific.
return {
  OLD_ROD = {
    { level = 5, species = "GOLDEEN" },
    { level = 5, species = "POLIWAG" },
  },
  GOOD_ROD = {
    { level = 20, species = "HORSEA" },
    { level = 20, species = "KRABBY" },
  },
  SUPER_ROD = {
    CELADON_CITY = {
      { level = 20, species = "GOLDEEN" },
      { level = 25, species = "GOLDEEN" },
      { level = 30, species = "GOLDEEN" },
      { level = 25, species = "GRIMER" },
    },
    CERULEAN_CAVE_1F = {
      { level = 55, species = "SEAKING" },
      { level = 55, species = "POLIWRATH" },
      { level = 55, species = "CLOYSTER" },
      { level = 55, species = "STARMIE" },
    },
    CERULEAN_CAVE_B1F = {
      { level = 60, species = "SEAKING" },
      { level = 60, species = "KINGLER" },
      { level = 60, species = "CLOYSTER" },
      { level = 60, species = "STARMIE" },
    },
    CERULEAN_CITY = {
      { level = 25, species = "GOLDEEN" },
      { level = 30, species = "GOLDEEN" },
      { level = 30, species = "SEAKING" },
      { level = 40, species = "SEAKING" },
    },
    CINNABAR_ISLAND = {
      { level = 35, species = "STARYU" },
      { level = 35, species = "TENTACOOL" },
      { level = 30, species = "STARYU" },
      { level = 35, species = "TENTACRUEL" },
    },
    FUCHSIA_CITY = {
      { level = 5, species = "MAGIKARP" },
      { level = 10, species = "MAGIKARP" },
      { level = 15, species = "MAGIKARP" },
      { level = 20, species = "GYARADOS" },
    },
    PALLET_TOWN = {
      { level = 25, species = "STARYU" },
      { level = 25, species = "TENTACOOL" },
      { level = 30, species = "STARYU" },
      { level = 30, species = "TENTACRUEL" },
    },
    ROUTE_10 = {
      { level = 25, species = "KRABBY" },
      { level = 30, species = "KRABBY" },
      { level = 30, species = "HORSEA" },
      { level = 35, species = "KINGLER" },
    },
    ROUTE_11 = {
      { level = 25, species = "TENTACOOL" },
      { level = 25, species = "TENTACOOL" },
      { level = 30, species = "TENTACOOL" },
      { level = 35, species = "HORSEA" },
    },
    ROUTE_12 = {
      { level = 30, species = "HORSEA" },
      { level = 25, species = "HORSEA" },
      { level = 30, species = "SEADRA" },
      { level = 35, species = "SEADRA" },
    },
    ROUTE_13 = {
      { level = 25, species = "HORSEA" },
      { level = 30, species = "HORSEA" },
      { level = 30, species = "TENTACRUEL" },
      { level = 30, species = "SEADRA" },
    },
    ROUTE_17 = {
      { level = 25, species = "TENTACOOL" },
      { level = 30, species = "TENTACOOL" },
      { level = 30, species = "SHELLDER" },
      { level = 35, species = "SHELLDER" },
    },
    ROUTE_18 = {
      { level = 25, species = "TENTACOOL" },
      { level = 30, species = "SHELLDER" },
      { level = 35, species = "SHELLDER" },
      { level = 35, species = "SHELLDER" },
    },
    ROUTE_19 = {
      { level = 25, species = "TENTACOOL" },
      { level = 30, species = "STARYU" },
      { level = 30, species = "TENTACOOL" },
      { level = 35, species = "TENTACRUEL" },
    },
    ROUTE_20 = {
      { level = 20, species = "TENTACOOL" },
      { level = 20, species = "TENTACRUEL" },
      { level = 30, species = "STARYU" },
      { level = 40, species = "TENTACRUEL" },
    },
    ROUTE_21 = {
      { level = 15, species = "TENTACOOL" },
      { level = 20, species = "STARYU" },
      { level = 30, species = "TENTACOOL" },
      { level = 30, species = "TENTACRUEL" },
    },
    ROUTE_22 = {
      { level = 10, species = "POLIWAG" },
      { level = 15, species = "POLIWAG" },
      { level = 20, species = "POLIWAG" },
      { level = 25, species = "POLIWHIRL" },
    },
    ROUTE_23 = {
      { level = 25, species = "POLIWAG" },
      { level = 30, species = "POLIWAG" },
      { level = 30, species = "POLIWHIRL" },
      { level = 40, species = "POLIWHIRL" },
    },
    ROUTE_24 = {
      { level = 35, species = "GOLDEEN" },
      { level = 30, species = "SEAKING" },
      { level = 35, species = "SEAKING" },
      { level = 30, species = "SEAKING" },
    },
    ROUTE_25 = {
      { level = 25, species = "KRABBY" },
      { level = 30, species = "KRABBY" },
      { level = 35, species = "KINGLER" },
      { level = 15, species = "DRATINI" },
    },
    ROUTE_4 = {
      { level = 30, species = "GOLDEEN" },
      { level = 35, species = "GOLDEEN" },
      { level = 30, species = "SEAKING" },
      { level = 35, species = "SEAKING" },
    },
    ROUTE_6 = {
      { level = 30, species = "GOLDEEN" },
      { level = 35, species = "GOLDEEN" },
      { level = 30, species = "SEAKING" },
      { level = 35, species = "SEAKING" },
    },
    SAFARI_ZONE_CENTER = {
      { level = 10, species = "MAGIKARP" },
      { level = 15, species = "MAGIKARP" },
      { level = 20, species = "DRATINI" },
      { level = 30, species = "DRAGONAIR" },
    },
    SAFARI_ZONE_EAST = {
      { level = 10, species = "MAGIKARP" },
      { level = 15, species = "MAGIKARP" },
      { level = 20, species = "GYARADOS" },
      { level = 25, species = "DRATINI" },
    },
    SAFARI_ZONE_NORTH = {
      { level = 10, species = "MAGIKARP" },
      { level = 15, species = "MAGIKARP" },
      { level = 20, species = "GYARADOS" },
      { level = 25, species = "DRATINI" },
    },
    SAFARI_ZONE_WEST = {
      { level = 10, species = "MAGIKARP" },
      { level = 15, species = "MAGIKARP" },
      { level = 20, species = "GYARADOS" },
      { level = 25, species = "DRATINI" },
    },
    SEAFOAM_ISLANDS_B3F = {
      { level = 35, species = "KRABBY" },
      { level = 35, species = "STARYU" },
      { level = 40, species = "KINGLER" },
      { level = 40, species = "STARYU" },
    },
    SEAFOAM_ISLANDS_B4F = {
      { level = 40, species = "KINGLER" },
      { level = 40, species = "STARYU" },
      { level = 35, species = "OMANYTE" },
      { level = 35, species = "KABUTO" },
    },
    VERMILION_CITY = {
      { level = 25, species = "TENTACOOL" },
      { level = 30, species = "TENTACOOL" },
      { level = 30, species = "KRABBY" },
      { level = 30, species = "HORSEA" },
    },
    VERMILION_DOCK = {
      { level = 30, species = "TENTACOOL" },
      { level = 30, species = "TENTACRUEL" },
      { level = 35, species = "STARYU" },
      { level = 30, species = "SHELLDER" },
    },
    VIRIDIAN_CITY = {
      { level = 15, species = "POLIWAG" },
      { level = 20, species = "POLIWAG" },
      { level = 25, species = "POLIWAG" },
      { level = 30, species = "POLIWAG" },
    },
  },
}
