-- Yellow Legacy v1.0.10 base-stat changes only.
-- Every omitted stat and species field remains live base data.
return {
  ARBOK = { baseStats = { hp = 62, attack = 95, speed = 90 } },
  CHARIZARD = { baseStats = { special = 95 } },
  CHARMANDER = { baseStats = { special = 55 } },
  CHARMELEON = { baseStats = { special = 70 } },
  CLEFABLE = { baseStats = { special = 95 } },
  DIGLETT = { baseStats = { attack = 70 } },
  DUGTRIO = { baseStats = { attack = 90 } },
  EEVEE = { baseStats = { hp = 70, attack = 65, defense = 65, special = 70 } },
  FARFETCHD = { baseStats = { hp = 62, attack = 75, defense = 65, special = 68, speed = 70 } },
  GLOOM = { baseStats = { hp = 70 } },
  GOLBAT = { baseStats = { speed = 100 } },
  HITMONCHAN = { baseStats = { hp = 60, attack = 50, special = 105 } },
  HITMONLEE = { baseStats = { hp = 65, defense = 70, special = 60, speed = 93 } },
  LICKITUNG = { baseStats = { hp = 95, attack = 70, defense = 85, special = 75 } },
  MAGMAR = { baseStats = { special = 95 } },
  MAROWAK = { baseStats = { special = 80 } },
  MUK = { baseStats = { special = 85 } },
  ODDISH = { baseStats = { hp = 50 } },
  ONIX = { baseStats = { hp = 75, attack = 80, special = 65, speed = 85 } },
  PIKACHU = { baseStats = { hp = 60, defense = 50, special = 70 } },
  PONYTA = { baseStats = { speed = 100 } },
  PORYGON = { baseStats = { hp = 75, attack = 70, special = 95 } },
  RAPIDASH = { baseStats = { speed = 115 } },
  VENOMOTH = { baseStats = { attack = 75, special = 95, speed = 100 } },
  VILEPLUME = { baseStats = { hp = 90 } },
  VULPIX = { baseStats = { hp = 45, defense = 45, special = 70, speed = 75 } },
  WIGGLYTUFF = { baseStats = { defense = 55, special = 85 } },
}
