return {
  rom = {
    id = "rom",
    label = "ROM",
    genderPresentation = nil,
  },
  frlg_red = {
    id = "frlg_red",
    label = "FRLG RED (MALE)",
    genderPresentation = "male",
    generation = 3,
    game = "Pokemon FireRed / LeafGreen",
    player = {
      walk = { path = "frlg_red_walk.png", frameW = 16, frameH = 32,
        frames = 12, anchorX = 8, anchorY = 32 },
      bike = { path = "frlg_red_bike.png", frameW = 32, frameH = 32,
        frames = 12, anchorX = 16, anchorY = 32 },
      surf = { path = "frlg_red_surf.png", frameW = 32, frameH = 32,
        frames = 6, anchorX = 16, anchorY = 32 },
      front = { path = "frlg_red_front.png", frameW = 64, frameH = 64,
        frames = 1, anchorX = 32, anchorY = 64 },
      back = { path = "frlg_red_back.png", frameW = 64, frameH = 64,
        frames = 1, anchorX = 32, anchorY = 64 },
      main_menu = { path = "frlg_red_main_menu.png", frameW = 64,
        frameH = 96, frames = 1, anchorX = 32, anchorY = 96 },
    },
  },
  frlg_leaf = {
    id = "frlg_leaf",
    label = "FRLG LEAF (FEMALE)",
    genderPresentation = "female",
    generation = 3,
    game = "Pokemon FireRed / LeafGreen",
    player = {
      walk = { path = "frlg_leaf_walk.png", frameW = 16, frameH = 32,
        frames = 12, anchorX = 8, anchorY = 32 },
      bike = { path = "frlg_leaf_bike.png", frameW = 32, frameH = 32,
        frames = 12, anchorX = 16, anchorY = 32 },
      surf = { path = "frlg_leaf_surf.png", frameW = 32, frameH = 32,
        frames = 6, anchorX = 16, anchorY = 32 },
      front = { path = "frlg_leaf_front.png", frameW = 64, frameH = 64,
        frames = 1, anchorX = 32, anchorY = 64 },
      back = { path = "frlg_leaf_back.png", frameW = 64, frameH = 64,
        frames = 1, anchorX = 32, anchorY = 64 },
      main_menu = { path = "frlg_leaf_main_menu.png", frameW = 64,
        frameH = 96, frames = 1, anchorX = 32, anchorY = 96 },
    },
  },
}
