-- Gen 1 opponent classes with direct FRLG equivalents in the supplied sheet.
-- Professor Oak and Yellow Jessie/James intentionally retain ROM portraits.
return {
  OPP_YOUNGSTER = "youngster",
  OPP_BUG_CATCHER = "bug_catcher",
  OPP_LASS = "lass",
  OPP_SAILOR = "sailor",
  OPP_JR_TRAINER_M = "camper",
  OPP_JR_TRAINER_F = "picnicker",
  OPP_POKEMANIAC = "pokemaniac",
  OPP_SUPER_NERD = "super_nerd",
  OPP_HIKER = "hiker",
  OPP_BIKER = "biker",
  OPP_BURGLAR = "burglar",
  OPP_ENGINEER = "engineer",
  OPP_FISHER = "fisherman",
  OPP_SWIMMER = "swimmer_m",
  OPP_CUE_BALL = "cue_ball",
  OPP_GAMBLER = "gamer",
  OPP_BEAUTY = "beauty",
  OPP_PSYCHIC = "psychic_m",
  OPP_ROCKER = "rocker",
  OPP_JUGGLER = "juggler",
  OPP_TAMER = "tamer",
  OPP_BIRD_KEEPER = "bird_keeper",
  OPP_BLACKBELT = "black_belt",
  OPP_RIVAL1 = "rival_early",
  OPP_SCIENTIST = "scientist",
  OPP_GIOVANNI = "giovanni",
  OPP_ROCKET = "rocket_grunt_m",
  OPP_COOLTRAINER_M = "cooltrainer_m",
  OPP_COOLTRAINER_F = "cooltrainer_f",
  OPP_BRUNO = "bruno",
  OPP_BROCK = "brock",
  OPP_MISTY = "misty",
  OPP_LT_SURGE = "lt_surge",
  OPP_ERIKA = "erika",
  OPP_KOGA = "koga",
  OPP_BLAINE = "blaine",
  OPP_SABRINA = "sabrina",
  OPP_GENTLEMAN = "gentleman",
  OPP_RIVAL2 = "rival_late",
  OPP_RIVAL3 = "champion_rival",
  OPP_LORELEI = "lorelei",
  OPP_CHANNELER = "channeler",
  OPP_AGATHA = "agatha",
  OPP_LANCE = "lance",
}
